on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/setup
    - run: echo Done
      shell: bash
