name: CI

on: [push, pull_request]

env:
  CACHE_IMAGE: fmrcampos/docker-ci-cache
  GPR_CACHE_IMAGE: docker.pkg.github.com/${{ github.repository }}/docker-ci-cache
  CACHE_SEED: 1
  NODE_VERSION: 14.4.0

jobs:
  test:
    runs-on: ubuntu-latest
    container: fmrcampos/docker-ci-cache:stage
    services:
      postgres:
        image: postgres:10.1
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache pip dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-pip-deps-dh
        with:
          path: ./.cache/pip
          key: ${{ runner.os }}-${{ env.CACHE_SEED }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.CACHE_SEED }}-${{ github.job }}-${{ env.cache-name }}-
            ${{ runner.os }}-${{ env.CACHE_SEED }}-${{ github.job }}-
            ${{ runner.os }}-${{ env.CACHE_SEED }}-
            ${{ runner.os }}-

      - name: Cache node version manager
        uses: actions/cache@v2
        env:
          cache-name: cache-nvm-dh
        with:
          path: ~/.nvm/versions/
          key: ${{ runner.os }}-build-${{ env.CACHE_SEED }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_SEED }}-${{ github.job }}-${{ env.cache-name }}-
            ${{ runner.os }}-build-${{ env.CACHE_SEED }}-${{ github.job }}-
            ${{ runner.os }}-build-${{ env.CACHE_SEED }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-npm-modules-dh
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_SEED }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_SEED }}-${{ github.job }}-${{ env.cache-name }}-
            ${{ runner.os }}-build-${{ env.CACHE_SEED }}-${{ github.job }}-
            ${{ runner.os }}-build-${{ env.CACHE_SEED }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          apt-get update && apt-get -y install make locales build-essential curl libpq-dev autoconf
          apt -y install libcurl4-openssl-dev libssl-dev pkg-config

      - name: Set locale
        run: |
          echo "LC_ALL=en_US.UTF-8" >> /etc/environment
          echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
          echo "LANG=en_US.UTF-8" > /etc/locale.conf
          locale-gen en_US.UTF-8

      - name: Install pip requirements
        run: |
          mkdir ./.cache && mkdir ./.cache/pip
          chown -R $(whoami) ./.cache/pip
          pip install -U pip setuptools wheel --cache-dir ./.cache/pip
          pip install -r requirements.txt --cache-dir ./.cache/pip
          pip install -r requirements/dev.txt --cache-dir ./.cache/pip
          
      - name: Setup node
        run: |
          curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm" 
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          nvm install $NODE_VERSION
          npm i -g npm
          npm install -g gulp-cli
          npm ci

      - name: Run tests
        run: |
          python -m coverage run -m pytest --strict --postgresql-host postgres
          python -m coverage html
          python -m coverage report -m --fail-under 100
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432

  lint:
    runs-on: ubuntu-latest
    container: fmrcampos/docker-ci-cache:stage
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Lint
        run: |
          apt-get update && apt-get install make
          make lint ACTIONS=true

  docs:
    runs-on: ubuntu-latest
    container: fmrcampos/docker-ci-cache:stage
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Documentation
        run: |
          apt-get update && apt-get install make
          make docs
  
  deps:
    runs-on: ubuntu-latest
    container: fmrcampos/docker-ci-cache:stage
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache pip dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-pip-deps-dh
        with:
          path: ./.cache/pip
          key: ${{ runner.os }}-${{ env.CACHE_SEED }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.CACHE_SEED }}-${{ github.job }}-${{ env.cache-name }}-
            ${{ runner.os }}-${{ env.CACHE_SEED }}-${{ github.job }}-
            ${{ runner.os }}-${{ env.CACHE_SEED }}-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          apt-get update && apt-get -y install build-essential make libpq-dev
          apt -y install libcurl4-openssl-dev libssl-dev pkg-config
          mkdir ./.cache && mkdir ./.cache/pip
          chown -R $(whoami) ./.cache/pip
          pip install -U pip setuptools wheel --cache-dir ./.cache/pip
          pip install -r requirements.txt --cache-dir ./.cache/pip
          pip install -r requirements/dev.txt --cache-dir ./.cache/pip

      - name: Check dependencies
        run: make deps

  licenses:
    runs-on: ubuntu-latest
    container: fmrcampos/docker-ci-cache:stage
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Check licenses
        run: bin/licenses
  
  translations:
    runs-on: ubuntu-latest
    container: fmrcampos/docker-ci-cache:stage
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Check translations
        run: |
          apt-get update && apt-get -y install make
          make translations

  static-lint:
    runs-on: ubuntu-latest
    container: fmrcampos/docker-ci-cache:static
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Static Lint Check
        run: |
          npm install eslint --save-dev
          ./node_modules/.bin/eslint 'warehouse/static/js/**' '**.js' 'tests/frontend/**' --ignore-pattern 'warehouse/static/js/vendor/**'
          ./node_modules/.bin/sass-lint --verbose

  static-tests:
    runs-on: ubuntu-latest
    container: fmrcampos/docker-ci-cache:static
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-static-dh
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_SEED }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_SEED }}-${{ github.job }}-${{ env.cache-name }}-
            ${{ runner.os }}-build-${{ env.CACHE_SEED }}-${{ github.job }}-
            ${{ runner.os }}-build-${{ env.CACHE_SEED }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Locale & Dependency Setup
        run: |
          apt-get update && apt-get -y install locales
          echo "LC_ALL=en_US.UTF-8" >> /etc/environment
          echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
          echo "LANG=en_US.UTF-8" > /etc/locale.conf
          locale-gen en_US.UTF-8
          npm install -D babel

      - name: Static Tests
        run: bin/static_tests

  static-pipeline:
    runs-on: ubuntu-latest
    container: fmrcampos/docker-ci-cache:static
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache node version manager
        uses: actions/cache@v2
        env:
          cache-name: cache-nvm-pipeline-dh
        with:
          path: ~/.nvm/versions/
          key: ${{ runner.os }}-build-${{ env.CACHE_SEED }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_SEED }}-${{ github.job }}-${{ env.cache-name }}-
            ${{ runner.os }}-build-${{ env.CACHE_SEED }}-${{ github.job }}-
            ${{ runner.os }}-build-${{ env.CACHE_SEED }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-static-dh
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_SEED }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_SEED }}-${{ github.job }}-${{ env.cache-name }}-
            ${{ runner.os }}-build-${{ env.CACHE_SEED }}-${{ github.job }}-
            ${{ runner.os }}-build-${{ env.CACHE_SEED }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Locale & Dependency Setup
        run: |
          apt-get update && apt-get -y install locales
          echo "LC_ALL=en_US.UTF-8" >> /etc/environment
          echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
          echo "LANG=en_US.UTF-8" > /etc/locale.conf
          locale-gen en_US.UTF-8
          npm install -D babel

      - name: Static Pipeline Check
        run: bin/static_pipeline