name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag warehouse-image:latest

      - name: Run the tests
        run: docker run warehouse-image:latest bin/tests --postgresql-host 127.0.0.1